### ISSUE TITLE
[help] For Intel pc!

### ISSUE THREAD

**Issue by NishchayKQ** [mohitbhatt-du/refresh_rate_fix_for_lig3#1]
hey i have the same pc's intel variant...do you recommend any software for retrieving my display specs? I cant seem to find any...

**Comment by mohitbhatt-du** [comment]
**Hello,**

When you open CRU tool, then it will show your default refresh rate, click on it then you can check your display specs. 
**As you can see below:** (I know intel don't have amd software just clearing that CRU is showing correct details)

![issue](https://github.com/mohitbhatt-du/refresh_rate_fix_for_lig3/assets/76405349/b8f3d53a-7dd9-47f8-a981-910403cfcb4b)


Also if you are trying to get 60hz then intel variant don't need to be enter display values manually, just create new refresh rate in CRU. It should work fine.

*Note:* In case display starts getting distortion or lines, use HDMI cable and connect to secondary monitor then set back to your default refresh rate from windows settings.

If you're still unclear, perhaps providing some screenshots would help to clarify.

Thanks!

**Comment by NishchayKQ** [comment]
hello! Thank you for the detailed reply!

> Also if you are trying to get 60hz then intel variant don't need to be enter display values manually, just create new refresh rate in CRU. It should work fine.

Is this option in add a standard resolution -> then select 1920x1080 with 60Hz?

![Screenshot 2024-04-02 131104](https://github.com/mohitbhatt-du/refresh_rate_fix_for_lig3/assets/108711354/3dc4e883-8fd0-4234-a676-652e540e76af)

**Comment by mohitbhatt-du** [comment]
**Use Detailed Resolution option!!**

**Step 1:**  Double click on default resolution in your case its *120.002Hz*
**Step 2:** Then on top there is an option to *copy*, just click it and close.
**Step 3:** Now click on *Add* then again on top there will be an option to *paste* (basically a button), click it then you will see all default values of your display will be copied then just edit refresh rate, for example - 60 or 90 as per your need. then click ok and restart your laptop. 

After that check windows settings display option, there should be another option for refresh rate. ie 120hz and 60hz (your desired refresh rate).

To check refresh rate is working go to this site - https://www.testufo.com/

It will look like this in CRU. Ignore the 135Hz because i overclocked my refresh rate.

![Screenshot 2024-04-02 132021](https://github.com/mohitbhatt-du/refresh_rate_fix_for_lig3/assets/76405349/bfa3e131-58f9-4377-84d7-fc5ff73176cb)

**Comment by NishchayKQ** [comment]
thank you so much! it worked
